use sas;
select * from categories;
select * from announcements;

truncate announcements;

show tables;

-- Check number of columns in a table
select COUNT(*) from information_schema.columns where table_name = 'announcements'; 
select COUNT(*) from information_schema.columns where table_name = 'categories';

-- Check data type of columns in table
select column_name, data_type from information_schema.columns where table_name= 'announcements';
select column_name, data_type from information_schema.columns where table_name= 'categories';

-- Check size of the column in table
select column_name, column_type from information_schema.columns where table_name= 'announcements';
select column_name, column_type from information_schema.columns where table_name= 'categories';

-- Check default field in a table
select column_name, column_default from information_schema.columns where table_name= 'announcements';
select column_name, column_default from information_schema.columns where table_name= 'categories';

-- Check null field in a table
select column_name, is_nullable from information_schema.columns where table_name= 'announcements';
select column_name, is_nullable from information_schema.columns where table_name= 'categories';

-- Check column keys in a table
select column_name, column_key from information_schema.columns where table_name= 'announcements';
select column_name, column_key from information_schema.columns where table_name= 'categories';

-- Check input column Title
Insert into `announcements`(`announcementId`, `announcementTitle`, `announcementDescription`, `publishDate`, `closeDate`, `announcementDisplay`, `categoryId`)
value (DEFAULT,  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi efficitur bibendum quam, ut volutpat orci varius ac. Aliquam bibendum mauris arcu, eget consequat massa pharetra in. Pellentesque porttitor libero id rhoncus bibendum. Vivamus massa nunc.", "Quisque quis metus quis dolor malesuada rutrum. Nulla dapibus laoreet ante a scelerisque porta ante.", DEFAULT, '2023-04-19 10:10:00', '2023-04-30 23:30:02', DEFAULT);

-- Check input column Desc
insert into `announcements`(`announcementId`, `announcementTitle`, `announcementDescription`,  `publishDate`, `closeDate`, `announcementDisplay`,`categoryId`)
value (DEFAULT, 
"Test Descriptions", 
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas dignissim metus non dui tincidunt lacinia. Morbi a blandit leo, non commodo augue. Aliquam fermentum vel velit vitae fermentum. Sed porttitor sit amet velit vel euismod. Donec lobortis scelerisque eros, quis tempor metus semper elementum. Fusce a augue ut felis interdum dapibus. Pellentesque nec commodo turpis. Vestibulum maximus dapibus libero, nec tristique purus consequat eu. Duis eu pretium magna, at volutpat mauris. Cras ullamcorper, eros efficitur ullamcorper ullamcorper, orci nisl luctus arcu, in finibus lacus sapien a augue. Aliquam fermentum libero et tortor euismod, auctor viverra dolor consectetur.
Praesent tempus erat sed ex egestas pellentesque. Nulla finibus turpis lacus, id volutpat ex laoreet luctus. Nunc eu vulputate enim, ut blandit purus. Suspendisse mattis libero eget orci tincidunt semper. Maecenas sem ex, accumsan scelerisque maximus et, suscipit sed arcu. Nulla vulputate posuere fermentum. Quisque eros metus, vehicula et lacus sit amet, laoreet dictum nibh. Morbi ac euismod nunc, eu finibus massa. Duis sollicitudin molestie lectus, sed fringilla lorem tincidunt nec. Mauris commodo finibus nisl, auctor cursus velit porta vel. Aenean nisi elit, hendrerit eget rhoncus nec, vestibulum commodo lorem. Proin sit amet efficitur tellus, quis pellentesque sapien. Duis eu risus dapibus, fermentum augue vitae, fringilla quam. Etiam sem lectus, posuere at dapibus sit amet, ornare sit amet augue. Nunc elementum, eros sed mattis porta, nisi augue fringilla tellus, in tincidunt felis enim a erat.
Nunc eu blandit est. Maecenas et lectus nisl. Sed et enim sit amet nisi eleifend semper. Integer semper cursus tortor, ac varius nunc sagittis sed. Quisque ut congue urna. In in orci leo. Quisque in lobortis ex. Cras ullamcorper viverra velit, eu porttitor neque accumsan commodo. Sed sit amet augue ut magna porttitor gravida lobortis sit amet elit. Vestibulum porttitor sed nulla a interdum. Nullam id fringilla diam. Duis vestibulum in risus et porta. Pellentesque eget sem ut augue venenatis rhoncus at ac erat. Aliquam sodales arcu nisl, id finibus ex consectetur in. Nullam commodo augue pretium eros elementum, non rhoncus lectus iaculis. Praesent sit amet venenatis libero, at molestie arcu.
Vestibulum ac ligula quis sapien consectetur molestie. Sed imperdiet bibendum quam id egestas. Donec luctus diam metus, nec scelerisque diam varius in. Ut lobortis pharetra elit tristique facilisis. Mauris elementum egestas dictum. Ut ac nulla vitae augue vestibulum blandit quis non est. Fusce lacinia quam sem, nec tempus lacus tempus a. Cras scelerisque nibh non felis bibendum, nec eleifend ante lacinia. Praesent pulvinar enim id ipsum gravida faucibus. Donec hendrerit, est eget accumsan bibendum, est dolor elementum sem, et auctor tortor enim at urna. Phasellus ultricies viverra aliquet. Quisque cursus ligula ac est placerat blandit. Quisque eu tristique justo.
Cras id mauris rhoncus lectus ullamcorper luctus. Duis sit amet pretium sem. Proin rhoncus enim ac mattis hendrerit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla ultrices tortor at fermentum tempus. Morbi id sagittis ligula, non consequat felis. Donec fermentum gravida blandit. Donec tempus magna sit amet mi ullamcorper vestibulum. Nulla ipsum nibh, viverra id ligula a, lacinia mattis neque. Etiam a arcu risus. Maecenas faucibus, eros eget posuere vehicula, velit libero lobortis mauris, ut accumsan orci libero ac tellus. Sed scelerisque viverra turpis a scelerisque.
Fusce tristique lacinia laoreet. Morbi vitae augue metus. In vel lacinia est. Fusce quis lectus sit amet nisi maximus maximus fringilla eget odio. Cras pellentesque libero et justo pellentesque sodales. Vivamus consequat lacinia nibh, eget facilisis dolor suscipit lobortis. Aenean lacinia fringilla orci, ac imperdiet orci sagittis ac.
Sed mattis ut eros id pretium. Integer at metus vel dolor faucibus dictum at vel ligula. Curabitur id viverra enim. Donec diam est, lacinia a commodo eget, accumsan in ex. Aliquam in justo augue. Phasellus vel dictum urna. Phasellus et aliquam est. Morbi faucibus varius dolor et pulvinar. Phasellus dignissim elementum ullamcorper. Nullam eget varius sem, at eleifend nulla.
Nulla facilisi. Suspendisse elementum ornare odio ac fermentum. Cras urna enim, tincidunt eget nisl viverra, consequat ultrices felis. Vestibulum pellentesque sollicitudin laoreet. Vivamus vitae ante lectus. Nam laoreet sagittis interdum. Integer iaculis justo ac urna ornare dignissim. Etiam posuere, sapien nec vestibulum rhoncus, arcu tortor egestas orci, sed feugiat massa metus id sapien. Cras in orci ut tortor interdum varius quis rhoncus sem. In interdum ullamcorper arcu eget vulputate. Suspendisse tempus eleifend imperdiet. In ultricies orci neque, vitae sollicitudin eros pretium quis. Phasellus ut sapien mattis mi dictum sagittis.
Sed interdum nisi massa, id vulputate quam facilisis eu. Cras non diam pellentesque neque porta finibus. Donec malesuada tempor tellus a imperdiet. Suspendisse scelerisque elit nulla, vel facilisis mi fringilla eget. Phasellus hendrerit fermentum neque quis dapibus. Duis et auctor ex, ut consectetur magna. Quisque lacinia justo vitae dui maximus ornare. Praesent nec volutpat turpis. Maecenas sed feugiat nisl, eu imperdiet magna. Fusce enim metus, condimentum non nisi sit amet, mattis cursus nulla. Nam mi mi, vulputate quis condimentum a, mollis ut nunc. Vivamus elementum eros et pulvinar vehicula. Nunc mattis arcu eu tincidunt luctus. Donec in sapien vulputate, sollicitudin sem ut, elementum nisl.
Curabitur sed maximus sapien. Etiam eu lorem efficitur, dignissim augue eget, rhoncus nunc. Phasellus fringilla pulvinar molestie. Aliquam sit amet arcu nisl. Etiam eget nisl lobortis, sodales sapien nec, luctus felis. Vestibulum faucibus hendrerit risus, eu placerat tellus commodo sit amet. Fusce feugiat vitae purus sed lobortis. Fusce eu diam ut ipsum accumsan bibendum. Nam mollis egestas accumsan. Duis pretium justo ac eros mollis malesuada. In in enim pellentesque, convallis metus nec, mollis nibh. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas id ligula eu mi mattis consequat sit amet id est. Pellentesque auctor sollicitudin mauris at mattis. Duis commodo risus augue, id efficitur orci mattis in. Suspendisse vitae elit at tellus vehicula lobortis.
Duis facilisis libero ullamcorper ex luctus, et lacinia dolor dictum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at nisi et diam semper finibus ac vel ex. Sed lacinia nibh quis molestie scelerisque. Suspendisse ornare pellentesque dui ac pretium. Fusce laoreet eget felis vel porta. In mollis commodo rutrum. Suspendisse potenti. Vivamus non felis tempor, ullamcorper elit vitae, faucibus eros. Proin mi est, auctor mollis euismod eget, tristique eget ex. Mauris eget augue sed felis accumsan sodales. Nullam erat felis, interdum quis hendrerit condimentum, tristique sed eros. Vestibulum tempus ipsum id mattis venenatis. Nam ullamcorper, sem commodo posuere facilisis, leo metus fringilla arcu, id maximus magna tortor facilisis magna.
Ut gravida dignissim diam, id semper augue tristique in. Morbi at sapien sed lorem posuere dapibus ut porttitor neque. Curabitur quis diam mauris. Maecenas id tortor orci. Maecenas commodo lectus sed tortor pretium, sed tincidunt lacus faucibus. Nunc condimentum, turpis quis mattis malesuada, ex sapien rhoncus libero, ac finibus tortor lorem quis tellus. Fusce lacinia ullamcorper nulla eget egestas. Etiam ipsum tellus, venenatis sit amet mi iaculis, mattis egestas tortor. Pellentesque placerat sapien a ligula blandit, ut finibus purus malesuada. Maecenas quis erat blandit est malesuada convallis vel sed ante. In tempor enim nisi, non pretium magna pretium ac. In hac habitasse platea dictumst. Mauris eget laoreet neque. Vestibulum mauris dui, consequat id nunc quis, imperdiet pharetra justo. Aliquam metus metus, vulputate id tortor ac, sodales pulvinar elit. Maecenas egestas sagittis est, commodo sollicitudin libero.
Donec scelerisque rutrum turpis, at fermentum nibh ultricies sit amet. Donec venenatis lorem augue. Donec volutpat venenatis dolor, quis volutpat est semper sed. In suscipit neque ut dolor posuere eleifend. Nulla malesuada suscipit sem. Ut auctor bibendum ex, ac tempus nisl suscipit ut. Nullam tincidunt ac risus eget luctus. Aenean erat nisi, iaculis rutrum hendrerit at, tincidunt quis metus. Mauris ex mauris, feugiat in massa sit amet, lobortis tempor elit. Donec maximus arcu libero. Mauris quis tincidunt velit. Cras maximus dolor risus, a rutrum justo tincidunt et. Ut nec gravida nunc, nec pulvinar mi.
Ut eu lectus interdum, vestibulum tortor eu, rutrum sapien. Nullam sodales, lacus a eleifend semper, augue lorem tincidunt turpis, tempus rutrum eros metus eu dolor. Nullam ac lorem sit amet felis elementum viverra. Vivamus sed consectetur tellus. Aliquam erat volutpat. Maecenas in dolor dictum, condimentum lacus ut, elementum nulla. Nullam sit amet tellus nulla. Quisque dapibus rhoncus iaculis. Nulla venenatis diam nec dignissim tempus. Integer auctor maximus dui, quis porttitor est bibendum vel. Sed semper consectetur neque sit amet varius. Ut vehicula volutpat orci, in rhoncus purus ornare maximus. Donec posuere mattis imperdiet. Nullam tempus turpis vel pellentesque dignissim.
Donec eu dapibus nulla. Aliquam erat volutpat. Aenean varius, lacus non tempor volutpat, urna enim faucibus nunc, quis aliquam velit justo sit amet ipsum. Praesent lobortis tellus in urna mollis lacinia. Sed interdum malesuada viverra. Ut laoreet accumsan dui. Vestibulum viverra porta nulla id laoreet. Sed tempus consequat lorem vestibulum facilisis. Mauris commodo mi arcu. Sed et risus feugiat, vulputate nibh et, porta mi. Maecenas fringilla blandit eros et consectetur. Etiam eget mi dignissim, interdum arcu eu, lacinia purus. Ut tempor nec.", 
DEFAULT, '2023-04-19 10:10:00', '2023-04-30 23:30:02', DEFAULT);

-- Check input not duplicate in Categories.
insert into `categories` (`categoryId`,`categoryName`) value (default , "ทั่วไป");


